version: '3.8'

services:
  frontend:
    image: pedrombmachado/ntu_lubuntu:comp20081
    ports:
      - "8080:8080"  
    depends_on:
      - loadbalancer

  loadbalancer:
    image: pedrombmachado/ntu_lubuntu:comp20081
    ports:
      - "8081:8081"  

  fileserver1:
    image: pedrombmachado/ntu_lubuntu:comp20081
    environment:
      SERVER_ID: 1

  fileserver2:
    image: pedrombmachado/ntu_lubuntu:comp20081
    environment:
      SERVER_ID: 2

  fileserver3:
    image: pedrombmachado/ntu_lubuntu:comp20081
    environment:
      SERVER_ID: 3

  fileserver4:
    image: pedrombmachado/ntu_lubuntu:comp20081
    environment:
      SERVER_ID: 4